services:
  - type: web
    name: chamado-app
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
